apiVersion: v1
kind: Namespace
metadata:
  name: devops-toolkit-production
---
apiVersion: v1
kind: Namespace
metadata:
  name: devops-toolkit-staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: devops-toolkit-qa
---
apiVersion: v1
kind: Namespace
metadata:
  name: devops-toolkit-dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
