apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-cert
  namespace: nginx-gateway
spec:
  secretName: grafana-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-gateway
  dnsNames:
  - grafana.devops-toolkit.dremer10.com
